# Generated by Django 4.2.27 on 2025-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('job', models.CharField(max_length=128, verbose_name='job')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='client', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last_name')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('year', models.CharField(max_length=128, verbose_name='year')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('value', models.IntegerField(verbose_name='percentage %')),
            ],
            options={
                'verbose_name': 'ProfessionalSkill',
                'verbose_name_plural': 'ProfessionalSkills',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=64, verbose_name='language')),
                ('value', models.IntegerField(verbose_name='percentage %')),
            ],
            options={
                'verbose_name': 'TechnicalSkill',
                'verbose_name_plural': 'TechnicalSkills',
            },
        ),
        migrations.CreateModel(
            name='WorkLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Work Language',
                'verbose_name_plural': 'Work Languages',
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('year', models.CharField(max_length=128, verbose_name='year')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('languages', models.ManyToManyField(to='app_pages.worklanguagemodel')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('language', models.CharField(max_length=128, verbose_name='language')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('image1', models.ImageField(upload_to='portfolio', verbose_name='image1')),
                ('image2', models.ImageField(upload_to='portfolio', verbose_name='image2')),
                ('tags', models.ManyToManyField(related_name='portfolios', to='app_pages.portfoliotagmodel', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
