# Generated by Django 4.2.27 on 2025-12-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0002_resumemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image1',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image2',
            field=models.FileField(blank=True, upload_to='portfolio', verbose_name='image2'),
        ),
    ]
