# Generated by Django 4.2.27 on 2025-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0003_alter_portfoliomodel_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image1',
            field=models.ImageField(upload_to='portfolio', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image2',
            field=models.ImageField(upload_to='portfolio', verbose_name='image2'),
        ),
    ]
